CREATE TABLE [dbo].[AIFeatures]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	[ServiceName] NVARCHAR(MAX) NOT NULL,
	[ServiceStatus] BIT NOT NULL DEFAULT 0,
	[IsActive] BIT NOT NULL DEFAULT 1,
	[DateCreated] DATE NOT NULL DEFAULT GETDATE(),
	[CreatedBy] NVARCHAR(MAX) NOT NULL,
	[DateModified] DATE NOT NULL DEFAULT GETDATE(),
	[ModifiedBy] NVARCHAR(MAX) NOT NULL
)
