CREATE TABLE [dbo].[ErrorLog]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	[ErrorMessage] NVARCHAR(MAX) NOT NULL,
	[ErrorProcedure] NVARCHAR(MAX) NOT NULL,
	[ErrorLine] NVARCHAR(MAX) NOT NULL,
	[DateCreated] DATETIME NOT NULL DEFAULT GETUTCDATE()
)
