name: Deploy to Azure App Service Template

on:
    workflow_call:
        inputs:
            artifact_name:
                required: true
                type: string
                description: "Name of the artifact to download"
            artifact_path:
                required: true
                type: string
                description: "Path to extract the artifact"
            app_name:
                required: true
                type: string
                description: "Azure App Service name"
            slot_name:
                required: false
                type: string
                default: "production"
                description: "Deployment slot name"
        secrets:
            publish_profile:
                required: true
                description: "Azure App Service publish profile"

jobs:
    deploy:
        name: Deploy to Azure App Service
        runs-on: ubuntu-latest
        environment: Production
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: ${{ inputs.artifact_name }}
                  path: ${{ inputs.artifact_path }}

            - name: Deploy to Azure App Service
              uses: Azure/webapps-deploy@v2
              with:
                  app-name: ${{ inputs.app_name }}
                  slot-name: ${{ inputs.slot_name }}
                  publish-profile: ${{ secrets.publish_profile }}
                  package: ${{ inputs.artifact_path }}
