// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:FitGymTool.Infrastructure.DB.DataManager.MemberFeesDataManager.GetCurrentMonthFeesAndRevenueStatusAsync~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{FitGymTool.Domain.Models.CurrentMonthFeesAndRevenueStatusDomain}}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:FitGymTool.Infrastructure.DB.DataManager.CommonDataManager.GetMappingsMasterDataAsync~System.Threading.Tasks.Task{System.ValueTuple{System.Collections.Generic.List{FitGymTool.Domain.Models.MappingDomain.FeesDurationMappingDomain},System.Collections.Generic.List{FitGymTool.Domain.Models.MappingDomain.FeesPaymentStatusMappingDomain},System.Collections.Generic.List{FitGymTool.Domain.Models.MappingDomain.MembershipStatusMappingDomain}}}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:FitGymTool.Infrastructure.DB.DataManager.MembersDataManager.AddNewMemberAsync(FitGymTool.Domain.Models.Members.AddMemberDomain)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:FitGymTool.Infrastructure.DB.DataManager.MembersDataManager.GetAllMembersAsync~System.Threading.Tasks.Task{System.Collections.Generic.List{FitGymTool.Domain.Models.Members.MemberDetailsDomain}}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:FitGymTool.Infrastructure.DB.DataManager.MembersDataManager.UpdateMemberAsync(FitGymTool.Domain.Models.Members.UpdateMemberDomain)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:FitGymTool.Infrastructure.DB.DataManager.MembersDataManager.DeleteMemberAsync(System.Int32)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:FitGymTool.Infrastructure.DB.DataManager.MembersDataManager.GetMemberByEmailIdAsync(System.String)~System.Threading.Tasks.Task{FitGymTool.Domain.Models.Members.MemberDetailsDomain}")]
