// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:FitGymTool.Persistence.Adapters.DataManager.CommonDataManager.GetMappingsMasterDataAsync~System.Threading.Tasks.Task{FitGymTool.Domain.DomainEntities.DerivedEntities.MappingMasterData}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:FitGymTool.Persistence.Adapters.DataManager.CommonDataManager.AddNewBugReportDataAsync(FitGymTool.Domain.DomainEntities.BugReportData)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:FitGymTool.Persistence.Adapters.DataManager.MembersDataManager.AddNewMemberAsync(FitGymTool.Domain.DomainEntities.MemberDetails)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:FitGymTool.Persistence.Adapters.DataManager.MembersDataManager.GetAllMembersAsync~System.Threading.Tasks.Task{System.Collections.Generic.List{FitGymTool.Domain.DomainEntities.MemberDetails}}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:FitGymTool.Persistence.Adapters.DataManager.MembersDataManager.GetMemberByEmailIdAsync(System.String)~System.Threading.Tasks.Task{FitGymTool.Domain.DomainEntities.MemberDetails}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:FitGymTool.Persistence.Adapters.DataManager.MembersDataManager.UpdateMemberDetailsAsync(FitGymTool.Domain.DomainEntities.MemberDetails)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:FitGymTool.Persistence.Adapters.DataManager.MembersDataManager.UpdateMembershipStatusAsync(FitGymTool.Domain.DomainEntities.MemberDetails)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:FitGymTool.Persistence.Adapters.DataManager.MemberFeesDataManager.GetCurrentMonthFeesAndRevenueStatusAsync~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{FitGymTool.Domain.DomainEntities.DerivedEntities.CurrentMonthFeesAndRevenueStatus}}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:FitGymTool.Persistence.Adapters.DataManager.MemberFeesDataManager.GetCurrentFeesStructureAsync~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{FitGymTool.Domain.DomainEntities.FeesStructure}}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:FitGymTool.Persistence.Adapters.DataManager.MemberFeesDataManager.GetCurrentMembersFeesStatusAsync~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{FitGymTool.Domain.DomainEntities.DerivedEntities.CurrentMembersFeesStatus}}")]
