name: Deploy FitGymTool API

env:
    API_PROJECT_PATH: FitGymTool.API/FitGymTool.API.csproj

on:
    workflow_dispatch:

jobs:
    build-api:
        name: Build FitGymTool.API
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'workflow_dispatch' }}
        outputs:
            artifact_path: ${{ steps.set-artifact-path.outputs.path }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "9.0.x"

            - name: Install dependencies and build Solution
              run: |
                  dotnet restore ${{ env.API_PROJECT_PATH }}
                  dotnet build ${{ env.API_PROJECT_PATH }} --configuration Release --no-restore

            - name: Publish the project
              run: |
                  dotnet publish ${{ env.API_PROJECT_PATH }} --configuration Release --no-build --output ./publish-api

            - name: Set artifact path
              id: set-artifact-path
              run: echo "path=./publish-api" >> $GITHUB_OUTPUT

            - name: Upload API Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: api-artifact
                  path: ./publish-api

    deploy-api:
        name: Deploy FitGymTool.API
        runs-on: ubuntu-latest
        needs: build-api
        environment: Production
        steps:
            - name: Download API Artifact
              uses: actions/download-artifact@v4
              with:
                  name: api-artifact
                  path: ./publish-api

            - name: Deploy to Azure App Service
              uses: Azure/webapps-deploy@v2
              with:
                  app-name: app-webapi-fitgym-tool
                  slot-name: production
                  publish-profile: ${{ secrets.AZURE_WEBAPI_PUBLISH_PROFILE }}
                  package: ./publish-api
