name: Build and Deploy FitGymTool

env:
    API_PROJECT_PATH: FitGymTool.API/FitGymTool.API.csproj
    WEB_PROJECT_PATH: FitGymTool.UI
    DATABASE_PROJECT_PATH: FitGymTool.Database/FitGymTool.Database.sqlproj

on:
    workflow_dispatch:
        inputs:
            deploy_api:
                description: "FitGymTool.API"
                required: false
                default: true
                type: boolean

            deploy_web:
                description: "FitGymTool.UI"
                required: false
                default: true
                type: boolean

            deploy_database:
                description: "FitGymTool.Database"
                required: false
                default: true
                type: boolean

jobs:
    build-api:
        name: Build FitGymTool.API
        if: ${{ inputs.deploy_api }}
        uses: ./.github/workflows/build-dotnet.yml
        with:
            project_path: ${{ env.API_PROJECT_PATH }}
            dotnet_version: "9.0.x"
            output_path: ./publish-api
            artifact_name: api-artifact

    deploy-api:
        name: Deploy FitGymTool.API
        needs: build-api
        if: ${{ inputs.deploy_api }}
        uses: ./.github/workflows/deploy-azure-app-service.yml
        with:
            artifact_name: api-artifact
            artifact_path: ./publish-api
            app_name: app-webapi-fitgym-tool
            slot_name: production
        secrets:
            publish_profile: ${{ secrets.AZURE_WEBAPI_PUBLISH_PROFILE }}

    build-web:
        name: Build FitGymTool.UI
        if: ${{ inputs.deploy_web }}
        uses: ./.github/workflows/build-angular.yml
        with:
            project_path: ${{ env.WEB_PROJECT_PATH }}
            node_version: "22.x"
            build_command: "npm run build"

    deploy-web:
        name: Deploy FitGymTool.UI
        needs: build-web
        if: ${{ inputs.deploy_web }}
        runs-on: ubuntu-latest
        environment: Production
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy UI to Azure Web App
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
                  action: "upload"
                  app_location: ${{ env.WEB_PROJECT_PATH }}
                  output_location: "dist/FitGymTool.UI/browser"
              env:
                  NODE_VERSION: "22"

    build-database:
        name: Build FitGymTool.Database
        if: ${{ inputs.deploy_database }}
        uses: ./.github/workflows/build-dotnet.yml
        with:
            project_path: ${{ env.DATABASE_PROJECT_PATH }}
            dotnet_version: "9.0.x"
            output_path: ./publish-db
            artifact_name: db-artifact

    deploy-database:
        name: Deploy FitGymTool.Database
        needs: build-database
        if: ${{ inputs.deploy_database }}
        uses: ./.github/workflows/deploy-azure-sql.yml
        with:
            artifact_name: db-artifact
            artifact_path: ./publish-db
            dacpac_file: "./publish-db/FitGymTool.Database.dacpac"
        secrets:
            azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
            connection_string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
