name: Deploy to Azure Static Web App Template

on:
    workflow_call:
        inputs:
            project_path:
                required: true
                type: string
                description: "Path to the web project directory"
            output_location:
                required: true
                type: string
                description: "Build output location"
            node_version:
                required: false
                type: string
                default: "22"
                description: "Node.js version for deployment"
        secrets:
            api_token:
                required: true
                description: "Azure Static Web Apps API token"

jobs:
    deploy:
        name: Deploy to Azure Static Web App
        runs-on: ubuntu-latest
        environment: Production
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy to Azure Static Web App
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.api_token }}
                  action: "upload"
                  app_location: ${{ inputs.project_path }}
                  output_location: ${{ inputs.output_location }}
              env:
                  NODE_VERSION: ${{ inputs.node_version }}
